version: '3'

services:
  couchbase:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    volume:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8000:8000'
      - '9443:9443'

volumes:
  portainer_data:
